### ISSUE TITLE
Informação sobre estabelecimentos

### ISSUE THREAD

**Issue by brunov1ctor** [mm-projetos/Servicos-Gerais#1]
Caso eu queira saber apenas o horário de funcionamento ou endereço por exemplo no campo de solicitar serviços de estabelecimentos sem solicitar um atendimento querendo apenas informações isso não seria possível.

**Comment by gusnunes** [comment]
Bom dia, colegas
Seria possível obter somente as informações sem precisar solicitar um atendimento, como está explicitado no diagrama. Quando o usuário busca e seleciona o estabelecimento/serviço, ele é direcionado à uma aba onde têm informações gerais, telefone para contato, endereço
