### ISSUE TITLE
Caso o serviço que eu precise não esteja disponível no momento

### ISSUE THREAD

**Issue by brunov1ctor** [mm-projetos/Servicos-Gerais#2]
Seria bom ter uma forma de guardar serviços que o usuário precise e estão indisponíveis no momento para lembra-ló de solicitar mais tarde.

**Comment by lucasaranha** [comment]
@brunov1ctor pode, por favor, dar mais detalhes da funcionalidade sugerida?

**Comment by brunov1ctor** [comment]
caso eu precise solicitar o serviço de alguma pessoa por exemplo chamar o encanador para fazer manutenção na minha casa mas no momento que eu for fazer o pedido este serviço não está disponível seja lá qual for o motivo, seria bom ter um lugar para os guardar serviços ou lembrar por meio de uma notificação para avisar quando o serviço estiver novamente disponível, isso facilitaria o uso caso exista um serviço preferencial por uma pessoa ou por uma empresa, pois não seria preciso ficar lembrado de solicitar novamente outra hora.

**Comment by lucasaranha** [comment]
Bruno, iremos considerar a sua sugestão.
